add_index:
    path:     /
    defaults: { _controller: "AppBundle:Advertisement:index" }
    methods:  GET

add_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Advertisement:show" }
    methods:  GET

add_new:
    path:     /new
    defaults: { _controller: "AppBundle:Advertisement:new" }
    methods:  [GET, POST]

add_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Advertisement:edit" }
    methods:  [GET, POST]

add_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Advertisement:delete" }
    methods:  DELETE
