AppBundle\Entity\Advertisement:
    type: entity
    table: advertisement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        content:
            type: string
            nullable: false
            length: 535
            options:
                fixed: false
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id

    manyToOne:
            category:
                targetEntity: Category
                inversedBy: adds
                joinColumn:
                    name: category_id
                    referencedColumnName: id

    manyToOne:
                user:
                    targetEntity: User
                    #inversedBy: adds
                    joinColumn:
                        name: user_id
                        referencedColumnName: id
    lifecycleCallbacks: {  }
